# Generated by Django 4.0.1 on 2022-01-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterecord', models.DateField()),
                ('schedule', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=10)),
                ('site', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default='0.0')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.persons')),
                ('recordscore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.persons')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sites')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'scores',
            },
        ),
    ]
