# Generated by Django 4.0.1 on 2022-01-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sites',
            options={'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
        migrations.AlterField(
            model_name='score',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.sites'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='site',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together={('email',)},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('site', 'recorder')},
        ),
        migrations.AlterUniqueTogether(
            name='sites',
            unique_together={('site',)},
        ),
        migrations.RemoveField(
            model_name='score',
            name='recordscore',
        ),
    ]
