# Generated by Django 4.0.1 on 2022-01-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_sites_options_alter_score_site_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together=set(),
        ),
    ]
