# Generated by Django 4.0.1 on 2022-01-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_persons_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persons',
            unique_together={('email',)},
        ),
    ]
